markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock, repo-metadata.html]

gems:
  - jekyll-mentions
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs"
  -
    scope:
      path: "docs/sensors"
      type: "pages"
    values:
      category: "sensors"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
      category: "projects"

kramdown:
    toc_levels: "2,3"
