markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock]

gems:
  - jekyll-mentions

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
      category: "projects"

kramdown:
    toc_levels: "2,3"
