markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock, repo-metadata.html]

gems:
  - jekyll-mentions
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "docs/"
      type: "pages"
    values:
      layout: "docs"
      category: "docs"
  -
    scope:
      path: "docs/drivers"
      type: "pages"
    values:
      layout: "docs"
      categories: "docs drivers"
  -
    scope:
      path: "docs/tutorials"
      type: "pages"
    values:
      categories: "tutorials docs"
  -
    scope:
      path: "docs/sensors"
      type: "pages"
    values:
      categories: "sensors docs"
  -
    scope:
      path: "docs/motors"
      type: "pages"
    values:
      categories: "motors docs"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
      category: "projects"

kramdown:
    toc_levels: "2,3"
