markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock]

gems:
  - jekyll-mentions

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "project"
      category: "projects"